### ISSUE TITLE
localized movie titles are not reliable

### ISSUE THREAD

**Issue by OttoKerner** [plexinc-agents/TheMovieDB.bundle#32]
Some movies get localized movie titles, some don't.
One that doesn't, is 'The Nut Job (2014)' (german: 'Operation: Nussknacker')

All other metadata is german, like description, poster, PG rating, release date...

My library is set to freebase, german.
The order of metadata agents in 'Settings' - 'Freebase' is
1. local 
2. TMDB (is set to 'Germany')
3. Freebase ('Localized Titles' is checked)
see screenshot

The file is a mkv - so no internal metadata influence.
Normally I have the OFDB.de (german metadata) agent active and above TMDB, but I explicitly tested also with OFDB.de deactivated. The issue persisted.
Between tests I removed the file, emptied trash, cleaned bundles ... etc.

Screenshots show, that TMDB has a german title for this movie, while Freebase has not.
This may change soon because the movie is set for release in Germany.
![agents](https://cloud.githubusercontent.com/assets/10280992/5889149/0a144070-a41a-11e4-9b59-4a9db8502afd.png)
![edit_details](https://cloud.githubusercontent.com/assets/10280992/5889151/0a17f63e-a41a-11e4-98d1-ae4a60d5014d.png)
![freebase](https://cloud.githubusercontent.com/assets/10280992/5889150/0a15323c-a41a-11e4-8b4a-6d02db16ccec.png)
![tmdb](https://cloud.githubusercontent.com/assets/10280992/5889152/0a1864ca-a41a-11e4-91f7-c418b866afa9.png)

Media server log & media scanner log:
https://dl.dropboxusercontent.com/u/71309108/nutjob_logfiles.zip

**Comment by sander1** [comment]
Thanks for the report! I can replicate the issue with the Freebase agent as primary agent and the order of the agents set to:
- Local Media Assets
- The Movie Database (which has the correct German title)
- Freebase

Language is set to German for the movie library.

The problem is that somehow the Local Media Assets agent sets the title of the movie (and since it's on top of the list it is allowed to). The question is, where is that title coming from (as the name of the directory and (test)file on my system are in German: `Operation Nussknacker (2014)/Operation Nussknacker (2014).mkv`

Disabling the Local Media Assets agent gives the correct result.

![screen shot 2015-02-27 at 17 35 34](https://cloud.githubusercontent.com/assets/104684/6416619/ab3070c6-bea7-11e4-9dfe-752522a5e1ad.jpg)
