### ISSUE TITLE
some movies downloading only english data

### ISSUE THREAD

**Issue by NightowlKr** [plexinc-agents/TheMovieDB.bundle#33]
when searching themovedb agent, some movies downloading only english data
and  searching Freebase with themoviedb agent, 
downloaded english titles and detail of chacked language's data or english data

so, i tried to analyze the movies
As a result, the the urls of movies has been redirected to added the movie's name.

example
https://www.themoviedb.org/movie/345670 > https://www.themoviedb.org/movie/345670-minor-views
https://www.themoviedb.org/movie/340067 > https://www.themoviedb.org/movie/340067-wooriegen-oneuli-ubda

plz cheacking this issue.

**Comment by sander1** [comment]
The redirect doesn't matter because we're not using the website to get our metadata from (we're using the Movie Database API).

The Movie Database agent falls back to English if it doesn't find metadata in the selected language. What are your library settings? Primary agent and order of the other agents, and the language setting?

![1](https://cloud.githubusercontent.com/assets/104684/8896635/7eec5216-3402-11e5-83ba-0a7aec89c82d.jpg)

![2](https://cloud.githubusercontent.com/assets/104684/8896636/8041bcbe-3402-11e5-88cf-a3ab488f5b7e.jpg)

![3](https://cloud.githubusercontent.com/assets/104684/8896637/81266cce-3402-11e5-85be-a778cb465c48.jpg)

**Comment by NightowlKr** [comment]
it's my old setting.

![001](https://cloud.githubusercontent.com/assets/5241111/8959583/a77d70ac-3646-11e5-9847-a628034cadb5.png)

![002](https://cloud.githubusercontent.com/assets/5241111/8959584/a780628a-3646-11e5-9b1f-826e7c5463b1.png)

![003](https://cloud.githubusercontent.com/assets/5241111/8959585/a780e93a-3646-11e5-933f-8afb77cbc232.png)
![004](https://cloud.githubusercontent.com/assets/5241111/8959586/a79cd442-3646-11e5-9f71-d28e920526a9.png)

![005](https://cloud.githubusercontent.com/assets/5241111/8959587/a79f7eb8-3646-11e5-8ea5-580913b36c5e.png)


and the detail of movies occursing the problem is there

![001](https://cloud.githubusercontent.com/assets/5241111/8959807/da82acf0-3647-11e5-9ffb-8abb2b7e4fc3.png)

![002](https://cloud.githubusercontent.com/assets/5241111/8959806/da80ba8a-3647-11e5-9f1c-e12b202336f1.png)

![003](https://cloud.githubusercontent.com/assets/5241111/8959808/daa04f26-3647-11e5-9caa-922adb0dc09d.png)

![004](https://cloud.githubusercontent.com/assets/5241111/8959809/daa46318-3647-11e5-8af9-4ef3e99e6259.png)


also, It is detail of work properly.

![005](https://cloud.githubusercontent.com/assets/5241111/8959931/6b18470c-3648-11e5-9bde-1e8fa35030e8.png)

![006](https://cloud.githubusercontent.com/assets/5241111/8959930/6b174ae6-3648-11e5-9601-7ca88984355e.png)

**Comment by davboc** [comment]
Same for me, I looking for Italian movie, 
english title: razorback
italian title: razorback: oltre l'urlo del demonio 

this is the page: https://www.themoviedb.org/movie/26178-razorback 

I try to change identification, search for the title and the result is right,  then I click on the title, and the movie title and description is all in English language 

Where is the error?

**Comment by maxGreenblatt** [comment]
HI @davboc - are you still having this problem? Are your library settings correct for your needs as mentioned in this comment: https://github.com/plexinc-agents/TheMovieDB.bundle/issues/33#issuecomment-125050092

**Comment by davboc** [comment]
Hi @maxGreenblatt yes my library settings are correct. There are two problems: a server cache and a client cache. The server cache require a few hours to be updated, after that I can manually update the client cache deleting the folder 
```
/volume1/Plex/Library/Application Support/Plex Media Server/Plug-in Support/Caches/com.plexapp.agents.themoviedb
```
Obviously if I wait a few hours without add the film after the edit of the movie on the movieDB site, Plex downloads the movie details for the first time (so it doesn't use cache) and all works well.

**Comment by maxGreenblatt** [comment]
Sorry - I don't really understand. Why is the cache the issue? It downloads english the first time you try, but it downloads the italian information if you try manually after the caches have been cleared?

**Comment by davboc** [comment]
Because if I have an English movie like the one in the example, and I translate it in Italian on the movieDB site, Plex still download the local version in the cache and the movie remain in English language. Indeed I edited the movie in my first post a week before making that post

**Comment by maxGreenblatt** [comment]
But if your library language is set to italian then it should match the english movie, but request italian content for it, so this is a bug and your cache shouldn't be affecting it. I'll look into this.

Thanks for the clarification!

**Comment by davboc** [comment]
Yes, this should be the right behavior.
Thanks for the support mate

**Comment by maxGreenblatt** [comment]
Hi @davboc -

I just had some time to look into this and I was unable to reproduce the problem. I created a library with the language set to italian and set TheMovieDB.org as my primary agent.

Then I added a fake movie file called `Razorback (1984).mkv` to the library. The file got scaned correctly, but was left unmatched because the best match (`Razorback: oltre l'urlo del demonio`) only had a score of `76`. I forget exactly what our automatch threshold is, but it's closer to 95+, I _believe_.

Can you take and post screenshots of your library settings (as depicted above) and also let me know what the file path is to your movie (ex: `C:\Movies\Razorback\Razorback (1984).avi`)?

Thanks!

**Comment by gregwym** [comment]
I think I'm experiencing similar issue. 

- Add a TV Show
- Matched with TMDb
- Update TMDb data with correct title translation + description for each episode
- Refresh/Rematch 
- Plex download out dated metadata
- Wait for a few weeks and confirmed the server cache is updated thru calling API directly
- Refresh/Rematch
- Plex still download out dated metadata from some where

I believe there is some kind of local cache in Plex that's preventing the new data being applied.

**Comment by gregwym** [comment]
I also wonder, is this the up to date source code for Plex TMDb agent? If so, are we encouraged to contribute to here to fix any problem we are encountering? Thanks.

**Comment by gregwym** [comment]
Turns out, deleting the agent http cache resolves the issue.
